version: '3.11'

services:
  flask:
    build: .
    volumes:
      - .:/app
    command: flask run
    ports:
      - "5050:5050"
    environment:
      FLASK_APP: "app.app.py"
      FLASK_ENV: "development"
      FLASK_DEBUG: 1
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "5050"